version: '2'
services:
  db:
    container_name: pinata_db
    image: postgres
    environment:
      POSTGRES_DB: pinata_db
      POSTGRES_USER: pinata
      POSTGRES_PASSWORD: pinata
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
  web:
    container_name: pinata_web
    environment:
      DATABASE_URL: postgres://pinata:pinata@db/pinata_db
      DJANGO_MANAGEPY_MIGRATE: "on"
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    links:
      - db:db
    ports:
      - "8000:8000"
