version: "2"
services:
  web:
    container_name: web
    restart: always
    build: ./web/
    expose:
      - "8000"
    links:
      - postgres:postgres
    env_file:
      - env
    volumes:
      - ./web:/data/web
    command: bash -c "./scripts/wait-for-it.sh 0.0.0.0:5432 -t 20 -- python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    volumes_from:
      - data
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./backups/postgresql:/backup
    env_file:
      - env
    expose:
      - "5432"
    ports:
      - "5432:5432"

  data:
    restart: always
    image: alpine
    volumes:
      - /var/lib/pgsql
    command: "true"
