version: "2"
services:
  web:
    container_name: web
    restart: always
    build: ./web/
    expose:
      - "8000"
    links:
      - postgres:postgres
    env_file:
      - env
    volumes:
      - ./web:/data/web
    command: "python manage.py runserver 0.0.0.0:8000"

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes_from:
      - web
    links:
      - web:web

  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    volumes_from:
      - data
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./backups/postgresql:/backup
    env_file:
      - env
    expose:
      - "5432"

    data:
      restart: always
      image: alpine
      volumes:
        - /var/lib/pgsql
      command: "true"
